name: build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install mops
        uses: ZenVoich/setup-mops@v1

      - name: install mops packages
        run: mops install

      - name: build canister
        run: $(mops toolchain bin moc) src/main.mo -o icrc_nft.wasm -c --idl --public-metadata candid:service --public-metadata candid:args $(mops sources)

      - uses: actions/upload-artifact@v2
        with:
          name: icrc_nft.wasm
          path: ./icrc_nft.wasm

      - uses: actions/upload-artifact@v2
        with:
          name: icrc_nft.did
          path: ./icrc_nft.did
