name: tests

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]


jobs:
  call_build:
    uses: ./.github/workflows/build.yml

  test:
    runs-on: ubuntu-22.04
    needs: call_build

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 'download wasm.gz'
        uses: actions/download-artifact@v3
        with:
          name: icrc_nft.wasm
          path: .

      - name: 'Download did'
        uses: actions/download-artifact@v3
        with:
          name: icrc_nft.did
          path: .

      - name: install dependencies
        run: bun i

      - name: run jest test
        run: bun run test